#!/bin/sh

# Copyright (C) Unex Technology Corporation - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential

dev=/dev/ttyAMA1
baud=230400
getver="\$PSTMGETPAR,1500*27\r\n"
setver="PSTMSETPAR"

cmdline="$*"
#echo $cmdline

killall -q -9 gpsd
gpsd=$(ps|grep gpsd|grep -v grep)
if [ x"$gpsd" != x ]; then
    echo "Failed to kill gpsd process: $gpsd"
    exit 1
fi

stty -F $dev raw speed $baud > /dev/null

exec 99<> $dev
printf "$getver" >&99 
cnt=0;
while read -t 5 line <&99; do
    curr_ver=$(echo "$line" | grep $setver)
    if [ $? -eq 0 ]; then
        ver_status=0;
        break;
    else
        cnt=$((cnt+1))
        if [ $cnt -eq 30 ]; then
            cnt=0
        fi
    fi
    if [ $cnt -eq 0 ]; then
        #echo -ne $getver > $dev
        printf "$getver" >&99
    fi
done 
exec 99>&-

echo "$curr_ver" | sed -e 's/\$PSTMSETPAR,[0-9]\+,\(.*\)\*\w\w/\1/'
