#!/bin/sh
 
# Copyright (C) Unex Technology Corporation - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential

dev=/dev/ttyAMA1
baud=230400
getver="\$PSTMGETPAR,1500*27\r\n"
setver="PSTMSETPAR"

cmdline="$*"
#echo $cmdline

usage()  
{  
    echo "Usage: $0 [option] GNSS_FW_FILE.bin"  
    echo "Option:"  
    echo "    -r: recover mode, using this mode when upgrading failed in normal mode"  
    exit 1  
} 

if [ $# -gt 2 ] || [ $# -lt 1 ]; then
    usage
fi

while [ x"$1" != x ]
do
    case "$1" in
        -r) recover="-r true" ;; # recover option
        *) file=$1 ;; # FW for upgrade
    esac
    shift
done

if [ ! -f $file ]; then
    echo "File not existed: $file"
    exit 1
else
    to_be_ver=$(strings $file |grep Release|tr -d '\r\n')
    echo "Version of new FW: $to_be_ver"
fi

killall -q -9 gpsd
gpsd=$(ps|grep gpsd|grep -v grep)
if [ x"$gpsd" != x ]; then
    echo "Failed to kill gpsd process: $gpsd"
    exit 1
fi

stty -F $dev raw speed $baud > /dev/null

if [ x"$recover" != x ]; then
    upgcmd="./teseo3-fw-update upgrade $recover -i $file -b 115200"
else
    upgcmd="./teseo3-fw-update upgrade -i $file"
fi

#echo $upgcmd
$upgcmd

if [ $? -eq 0 ]; then
    stty -F $dev raw speed $baud > /dev/null
    status=0
else
    status=-1
fi

ver_status=-1

if [ ! $status -eq -1 ]; then
    #open fd 99 for gnss serial port.
    exec 99<> $dev
    #echo -ne $getver > $dev
    #printf "$getver" > $dev
    printf "$getver" >&99 
    cnt=0;
    while read -t 5 line <&99; do
        curr_ver=$(echo "$line" | grep $setver)
        if [ $? -eq 0 ]; then
            ver_status=0;
            break;
        else
            cnt=$((cnt+1))
            if [ $cnt -eq 30 ]; then
                cnt=0
            fi
        fi
        if [ $cnt -eq 0 ]; then
            #echo -ne $getver > $dev
            printf "$getver" >&99
        fi
    done 
    # close fd 99
    exec 99>&-
fi

if [ $ver_status -eq 0 ]; then 
    printf "$curr_ver" | grep -q -F "$to_be_ver" 
    if [ $? -eq 0 ]; then
        echo "Successfully upgrade to new GNSS FW."
    else
        curr_ver=$(echo "$curr_ver" | sed -e 's/\$PSTMSETPAR,[0-9]\+,\(.*\)\*\w\w/\1/')
        echo "Failed to upgrade:"
        echo "    GNSS FW File: $to_be_ver"
        echo "    Current GNSS FW: $curr_ver"
    fi
fi
